- config.php
feat: change spread
(change .env)
> DS-5030_new_spread

- config.php
- src/1.0.0/js/common/user.js
- src/1.0.0/js/homeEcommerce.js
- src/1.0.0/js/user.js
- stages/ecommerce/pre/ecommerce.php
> DS-5038_integrate_form_flow

- ecommerce-registrado.php
- ecommerce.php
- sponsors-interna.php
- sponsors-registrado.php
- sponsors.php
- src/components/cacheSettings.php
- stages/ecommerce/pre/ecommerce-registrado.php
> DS-5047_fix_ecommerce_phase

- src/1.0.0/css/pages/previous-editions.css
> DS-5033-Previous-edition-v2

- index.php
- registrado.php
- sponsors.php
- src/1.0.0/js/dateCounter.js
- src/components/head-home.php
- stages/ecommerce/pre/ecommerce-registrado.php
- stages/ecommerce/pre/ecommerce.php
DS-5053-Pre-deploy-modifications
> DS-5053-Pre-deploy-modifications

- src/1.0.0/css/components/event-numbers.css
- stages/ecommerce/pre/ecommerce.php
DS-5056-Post-deploy-modifications
> DS-5056-Post-deploy-modifications

- services/register.php
- stages/ecommerce/pre/ecommerce.php
> DS-5059_fix_spread

- services/register.php
related to https://makingsense.atlassian.net/jira/software/projects/DS/boards/21?selectedIssue=DS-5063
> DS-5063 upate subscription list

- .docker/docker-compose.yml
related to; https://makingsense.atlassian.net/browse/DS-5041
> DS-5041 docker network

- stripe/controllers/StripeCustomersController.php
- stripe/createCustomer.php
- stripe/models/StripeCustomersDatabase.php
RELATED TO https://makingsense.atlassian.net/browse/DS-5041
> DS-5041 create customer endpoint

- stripe/controllers/StripeCustomersController.php
- stripe/createCustomer.php
- stripe/models/RegisteredDatabase.php
- stripe/models/StripeCustomersDatabase.php
https://makingsense.atlassian.net/browse/DS-5068
> DS-5068 registered model & add attr stripe

- config.php
- ecommerce-registrado.php
- ecommerce.php
- services/getRegisteredByEmail.php
- services/register.php
- src/1.0.0/js/common/formsValidators.js
- src/1.0.0/js/common/submitForm.js
- src/1.0.0/js/enums/eventsType.enum.js
- src/1.0.0/js/homeDigital.js
- src/1.0.0/js/homeEcommerce.js
- src/1.0.0/js/popUp.js
- src/1.0.0/js/previousEditions.js
- src/1.0.0/js/speakersInterna.js
- src/1.0.0/js/sponsors.js
- src/1.0.0/js/user.js
- src/components/cacheSettings.php
- utils/Relay.php
- utils/newDB.php
- utils/stripe/StripeCustomersController.php
- utils/stripe/StripeCustomersModel.php
[feat: add new flow for already registered users](https://github.com/FromDoppler/emms24/commit/2da6b39891231f478f1ca2a29cd4f8e2e02bbf03)
[feat: add events enum](https://github.com/FromDoppler/emms24/commit/7bb445dd63c6bdddbb1a13b64060f35dd4459c05)
[feat: add event name const for php](https://github.com/FromDoppler/emms24/commit/28b17f1533b22cee6fd6df251d89ed58dbd49c6f)
> DS-5074_ecommerce_current_register_flow

- utils/relay-templates/ecommerce/ecommerce-vip-template.html
> email-ecommerce-vip

- src/1.0.0/css/components/hellobar.css
- src/1.0.0/js/calendarBio.js
> ecommerce-layout-details

- ediciones-anteriores.php
- speaker-interna.php
- sponsors.php
- src/1.0.0/css/components/form.css
- src/1.0.0/js/common/switchForm.js
- src/1.0.0/js/enums/eventsType.enum.js
- src/1.0.0/js/homeEcommerce.js
- src/1.0.0/js/previousEditions.js
- src/1.0.0/js/speakersInterna.js
- src/1.0.0/js/sponsors.js
- stages/ecommerce/pre/ecommerce.php
feat: add new switch form logic
> DS-5086_add_switch_form

- admin/speakers/add_speakers.php
- admin/speakers/edit_speakers.php
- admin/speakers/view_speakers.php
https://makingsense.atlassian.net/browse/DS-5085
> DS-5085 admin title speakers

- admin/speakers/edit_speakers.php
- checkout-success.php
- checkout.php
https://makingsense.atlassian.net/browse/DS-5083
https://makingsense.atlassian.net/browse/DS-5085
> DS-5083 DS-5085 checkout succes & faqs & edit speakers adm

- src/components/companiesList.php
https://makingsense.atlassian.net/browse/DS-5099
> DS-5099 fix img sponsors

- stripe/controllers/StripeCustomersController.php
https://makingsense.atlassian.net/browse/DS-5106
> DS-5106 refactor stripe registration

- checkout.php
DS-5096 https://makingsense.atlassian.net/browse/DS-5096
> DS-5096 redirect if unregistered user

- admin/speakers/add_speakers.php
- admin/speakers/edit_speakers.php
https://makingsense.atlassian.net/browse/DS-5103
> DS-5103 admin speakers debate

- src/1.0.0/css/components/calendar.css
- src/components/speakers.php
> DS-5107_calendar_changes

- index.php
- registrado.php
- src/1.0.0/css/components/central-video.css
- src/1.0.0/css/components/features.css
- src/1.0.0/css/components/premium-content-banner.css
- src/1.0.0/css/components/prices-plans.css
- src/1.0.0/css/components/speakers-list.css
- src/1.0.0/css/general/constants.css
- src/1.0.0/css/pages/ecommerce.css
- src/1.0.0/css/pages/sponsors-promo.css
- stages/ecommerce/pre/ecommerce-registrado.php
- stages/ecommerce/pre/ecommerce.php
> DS-5111_fix_texts_styles

- src/1.0.0/js/mediaPartners.js
- stages/ecommerce/pre/ecommerce-registrado.php
- stages/ecommerce/pre/ecommerce.php
> DS-5108_hidden_benefits

- utils/relay-templates/ecommerce/ecommerce-pre-template.html
- utils/relay-templates/ecommerce/old/ecommerce-pre-template.html
> DS-5113_new_email_flow

- stages/ecommerce/during/ecommerce-registrado.php
- stages/ecommerce/during/ecommerce.php
https://makingsense.atlassian.net/browse/DS-5114
> DS-5114 during stage pages

- descarga-certificado.php
- src/1.0.0/js/certificate/certificateWorkshop.js
- src/1.0.0/js/common/certificate.js
- textify/certificate-emms2024.php
- textify/certificate-emms2024qa.php
> DS-5109_DS-5110_certificate

- src/1.0.0/css/pages/ecommerce.css
- stages/ecommerce/during/ecommerce-registrado.php
- stages/ecommerce/during/ecommerce.php
- stages/ecommerce/pre/ecommerce.php
feat: during first structure whitout desing
> DS-5115_during_v1

- src/components/cacheSettings.php
https://makingsense.atlassian.net/browse/DS-5118
> DS-5118 cache settings

- stages/ecommerce/post/ecommerce-registrado.php
- stages/ecommerce/post/ecommerce.php
https://makingsense.atlassian.net/browse/DS-5117
> DS-5117 post stage pages ecommerce

- stages/ecommerce/post/ecommerce-registrado.php
- stages/ecommerce/post/ecommerce.php
https://makingsense.atlassian.net/browse/DS-5119
> DS-5119 speakers change current event filter

- admin/speakers/add_speakers.php
- admin/speakers/edit_speakers.php
- admin/speakers/view_speakers.php
https://makingsense.atlassian.net/browse/DS-5120
> DS-5120 label input url youtube zoom

- config.php
- stripe/controllers/StripeCustomersController.php
- utils/Relay.php
- utils/relay-templates/ecommerce/ecommerce-during-vip-template.html
https://makingsense.atlassian.net/browse/DS-5122
> DS-5122 handle emails during

- src/1.0.0/js/certificate/certificateWorkshop.js
- src/components/speakers.php
- stages/ecommerce/during/ecommerce.php
> DS-5121_final_desing

- index.php
- registrado.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/css/components/hellobar.css
- src/1.0.0/css/components/hero-conference.css
- src/1.0.0/css/components/speakers-list.css
- src/1.0.0/css/general/constants.css
- src/1.0.0/css/pages/home.css
- src/components/companiesList.php
- src/components/speakers.php
- stages/ecommerce/during/ecommerce-registrado.php
- stages/ecommerce/during/ecommerce.php
> DS-5123_feedback_post_deplo

- src/1.0.0/css/components/hero-conference.css
- src/components/speakers.php
- stages/ecommerce/during/ecommerce.php
> DS-5126_fixes

- src/1.0.0/js/newDate.js
https://makingsense.atlassian.net/browse/DS-5131
> DS-5131 update script datetime event country

- src/1.0.0/css/components/hero-registration.css
> DS-5138_fix_content_style

- .docker/docker-compose.yml
- .gitignore
https://makingsense.atlassian.net/browse/DS-5171
> DS-5171 docker update

- index.php
dt index changes
https://makingsense.atlassian.net/browse/DS-5172
> DS-5172 dt index

- stripe/controllers/StripeCustomersController.php
- utils/Relay.php
- utils/relay-templates/ecommerce/ecommerce-post-vip-template.html
https://makingsense.atlassian.net/browse/DS-5132
> DS-5132 email post flow

- ediciones-anteriores-registrado.php
- src/1.0.0/css/pages/previous-editions.css
feat: add card in previous edition registered
Related to: #84  https://makingsense.atlassian.net/browse/DS-5175
> DS-5175_fix_previous_editions

- components/digital-trends/pre/benefit-icons.php
- components/digital-trends/pre/central-video.php
- components/digital-trends/pre/companies-list.php
- components/digital-trends/pre/digital-trends/head.php
- components/digital-trends/pre/digital-trends/hello-module.php
- components/digital-trends/pre/doppler-academy-banner.php
- components/digital-trends/pre/event-numbers.php
- components/digital-trends/pre/faqs.php
- components/digital-trends/pre/grid-event-types.php
- components/digital-trends/pre/hellobar-vip.php
- components/digital-trends/pre/hellobar.php
- components/digital-trends/pre/home/head.php
- components/digital-trends/pre/home/hello-module.php
- components/digital-trends/pre/premium-content.php
- components/digital-trends/pre/register-form.php
- components/digital-trends/pre/speakers-carousel.php
- components/digital-trends/pre/users-comments.php
- components/footer.php
- components/gtm.php
- components/head.php
- components/navbar-reg.php
- components/navbar-unreg.php
- components/share.php
https://makingsense.atlassian.net/browse/DS-5195
> DS-5195 components abstraction refactor

- pages/digital-trends/pre/digital-trends-registrado.php
- pages/digital-trends/pre/digital-trends.php
- pages/digital-trends/pre/home-registrado.php
- pages/digital-trends/pre/home.php
https://makingsense.atlassian.net/browse/DS-5177
> DS-5177 digital trends pages home & interna

- src/1.0.0/js/common/switchForm.js
- src/1.0.0/js/homeDigital.js
https://makingsense.atlassian.net/browse/DS-5196
> DS-5196 form login DT

- components/digital-trends/pre/register-withoutform.php
- pages/digital-trends/pre/digital-trends.php
- src/1.0.0/js/homeDigital.js
[add dt register without form](https://github.com/FromDoppler/emms24/commit/8056563d81251e00322ccfaf495e4f6f9c09dcda)
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5176)
> DS-5198 add dt register without form

- ediciones-anteriores-registrado.php
- ediciones-anteriores.php
- sponsors-promo.php
- sponsors-registrado.php
- sponsors.php
https://makingsense.atlassian.net/browse/DS-5199
> DS-5199 replace old links

- utils/relay-templates/dt/dt-pre-template.html
add new dt pre email
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5182)
> DS-5182 add dt pre email

- ediciones-anteriores-registrado.php
- ediciones-anteriores.php
feat: change card content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5175)
> DS-5175 change_card_content

- components/digital-trends/pre/register-withoutform.php
> DS-5198 fix marquee

- components/navbar-reg.php
- components/navbar-unreg.php
realted to: https://makingsense.atlassian.net/browse/DS-5199
> DS-5199 navbar detect active path

- components/digital-trends/pre/digital-trends/registrado/central-video.php
- pages/digital-trends/pre/digital-trends-registrado.php
https://makingsense.atlassian.net/browse/DS-5210
> DS-5210 dt registrado central video component

- components/digital-trends/pre/register-form.php
- ediciones-anteriores.php
- services/register.php
- sponsors.php
- src/1.0.0/js/common/submitForm.js
- utils/DB.php
- utils/Doppler.php
- utils/SpreadSheetGoogle.php
https://makingsense.atlassian.net/browse/DS-5212
> changes input form

- components/head.php
https://makingsense.atlassian.net/browse/DS-5193
> DS-5193 link to dhtrak && firebase messagin sw script

- components/digital-trends/pre/register-form.php
https://makingsense.atlassian.net/browse/DS-5235
> DS-5235 content changes

- .gitignore
- components/digital-trends/schedule/mobile-carousel.php
- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- components/digital-trends/schedule/speakers.php
- pages/digital-trends/pre/digital-trends-registrado.php
- pages/digital-trends/pre/digital-trends.php
https://makingsense.atlassian.net/browse/DS-5265
> DS-5265 schedule component

- admin/speakers/index.php
- admin/speakers/schedule-preview.php
- src/components/cacheSettings.php
https://makingsense.atlassian.net/browse/DS-5306
> DS-5306 admin schedule preview

- admin/speakers/add_speakers.php
- admin/speakers/edit_speakers.php
- components/digital-trends/schedule/schedule.php
- src/1.0.0/css/components/calendar.css
https://makingsense.atlassian.net/browse/DS-5306
> DS-5306 schedule style for admin preview

- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- pages/digital-trends/pre/digital-trends-registrado.php
- src/1.0.0/css/components/calendar.css
https://makingsense.atlassian.net/browse/DS-5308
> DS-5308 schedule feedback

- admin/speakers/add_speakers.php
- admin/speakers/edit_speakers.php
add succes story type in admin
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5325)
> DS-5325 add succes story in admin 

- components/digital-trends/schedule/mobile-carousel.php
- components/digital-trends/schedule/showSpeakersByDay.php
- src/1.0.0/css/components/calendar.css
add success story
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5324)
> DS-5324 add success story

- components/digital-trends/pre/checkout/faq.php
https://makingsense.atlassian.net/browse/DS-5329
> DS-5329 faq checkout

- checkout-success.php
- components/digital-trends/pre/checkout/checkout-success.php
- pages/digital-trends/pre/checkout-success.php
https://makingsense.atlassian.net/browse/DS-5330
> DS-5330 checkout success

- components/digital-trends/pre/digital-trends/video-ticketing.php
- pages/digital-trends/pre/digital-trends-registrado.php
- src/1.0.0/css/components/central-video.css
add video ticketing module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5322)
> DS-5322 add video ticketing module

- components/digital-trends/pre/digital-trends/vip-features.php
- pages/digital-trends/pre/digital-trends-registrado.php
- src/1.0.0/css/components/features.css
add vip pass module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5323)
> DS-5323 vip pass module

- components/digital-trends/pre/checkout/checkout.php
- components/digital-trends/pre/faqs.php
- pages/digital-trends/pre/digital-trends.php
https://makingsense.atlassian.net/browse/DS-5328
> DS-5328 fix event name

- components/digital-trends/pre/digital-trends/hello-module.php
- components/digital-trends/pre/register-form.php
- components/digital-trends/pre/register-withoutform.php
- components/marquee.php
- speaker-interna.php
- sponsors-promo.php
- stages/ecommerce/during/ecommerce-registrado.php
- stages/ecommerce/during/ecommerce.php
- stages/ecommerce/post/ecommerce-registrado.php
- stages/ecommerce/post/ecommerce.php
- stages/ecommerce/pre/ecommerce-registrado.php
- stages/ecommerce/pre/ecommerce.php
create marquee component
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5345)
> DS-5345 marquee component

- components/digital-trends/pre/digital-trends/hello-vip-module.php
- src/1.0.0/css/components/hero-registration.css
add vip hero module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5321)
> DS-5321 add vip hero

- components/digital-trends/pre/checkout/checkout-success.php
- components/digital-trends/pre/checkout/checkout.php
https://makingsense.atlassian.net/browse/DS-5347
> DS-5347 checkout y checkout success spinner on mount component

- utils/Relay.php
- utils/relay-templates/dt/dt-pre-vip-template.html
https://makingsense.atlassian.net/browse/DS-5334
> DS-5334 dt free vip emails

- components/digital-trends/pre/digital-trends/entry-plans.php
- pages/digital-trends/pre/digital-trends-registrado.php
- src/1.0.0/css/components/companies-list.css
- src/1.0.0/js/toggleVipElements.js
add vip modules logic
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5327)
> DS-5327 vip modules logic

- components/digital-trends/pre/register-form.php
- src/1.0.0/css/components/form.css
- src/1.0.0/css/components/hero-registration.css
show form in first view mobile
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5354)
> DS-5354 show form mobile first

- src/1.0.0/css/components/central-video.css
[change mobile video width](https://github.com/FromDoppler/emms24/commit/cbcccf9667cb12dc160c5aedfa66ed94f7cf8f2a)
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5353)
> DS-5353 fix mobile iframe

- components/digital-trends/pre/digital-trends/entry-plans.php
change entry plans content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5351)
> DS-5351 change entry plans

- components/digital-trends/pre/digital-trends/vip-features.php
- src/1.0.0/css/components/features.css
change vip features module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5350)
> DS-5350 edit vip features module

- components/digital-trends/pre/digital-trends/entry-plans.php
- components/digital-trends/schedule/schedule.php
- pages/digital-trends/pre/digital-trends-registrado.php
- pages/digital-trends/pre/digital-trends.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/css/components/central-video.css
change schedule
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5352)
> DS-5352 schedule changes

- components/digital-trends/pre/doppler-academy-banner.php
- components/digital-trends/pre/register-form.php
- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- components/sponsorsList.php
- pages/digital-trends/pre/digital-trends-registrado.php
- pages/digital-trends/pre/digital-trends.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/css/components/central-video.css
- src/1.0.0/css/components/prices-plans.css
- src/1.0.0/css/pages/previous-editions.css
- src/components/sponsorsList.php
apply final content and design fixes
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5348)
> DS-5348 final content

- components/digital-trends/schedule/mobile-carousel.php
- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- components/digital-trends/schedule/speakers.php
apply schedule demo changes
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5363)
> DS-5363 schedule changes

- components/digital-trends/pre/digital-trends/entry-plans.php
- components/digital-trends/pre/digital-trends/hello-vip-module.php
- components/digital-trends/pre/digital-trends/video-ticketing.php
- components/digital-trends/pre/digital-trends/vip-features.php
- src/1.0.0/css/components/features.css
- src/1.0.0/css/general/constants.css
apply demo feedback in vip modules
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5364)
> DS-5364 vip demo changes

- components/digital-trends/pre/checkout/checkout-success.php
https://makingsense.atlassian.net/browse/DS-5339
> DS-5339 env stripe server

- components/digital-trends/pre/checkout/faq.php
- components/digital-trends/pre/digital-trends/entry-plans.php
- components/digital-trends/pre/digital-trends/video-ticketing.php
- components/digital-trends/pre/digital-trends/vip-features.php
- components/digital-trends/schedule/schedule.php
- src/1.0.0/css/components/central-video.css
> hot_fix_post_deplo

- components/digital-trends/pre/register-form.php
change content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5367)
> DS-5367 change content

- pages/digital-trends/pre/digital-trends.php
change ui for old ecommerce users
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5370)
> DS-5370 fix register withoutform flow

- components/sponsorsList.php
- sponsors-registrado.php
- sponsors.php
https://makingsense.atlassian.net/browse/DS-5369
> DS-5369 hide sponsors list module

- src/components/gtm.php
- src/components/head.php
add gtm with hotjar
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5374)
> DS-5374 add gtm with hotjar

- src/1.0.0/css/pages/ecommerce.css
change background dt property
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5376)
> DS-5376 fix dt backgorund

- components/digital-trends/pre/register-form.php
- src/1.0.0/js/autoCompleteUserForm.js
add auto complete user forms with params
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5379)
> DS-5379_add_autocomplete_user_form

- src/1.0.0/js/homeDigital.js
add validation in dt form
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5381)
> DS-5381_add_validation_in_dt_form

- components/sponsorsList.php
- pages/digital-trends/pre/digital-trends-registrado.php
- pages/digital-trends/pre/digital-trends.php
https://makingsense.atlassian.net/browse/DS-5377
> DS-5377 show sponsors list component

- components/sponsorsList.php
- utils/DB.php
https://makingsense.atlassian.net/browse/DS-5377
> DS-5377 refactor sponsor list component

- components/digital-trends/pre/digital-trends/video-ticketing.php
https://makingsense.atlassian.net/browse/DS-5382
> DS-5382 update code video

- components/digital-trends/pre/checkout/checkout.php
https://makingsense.atlassian.net/browse/DS-5378
> DS-5378 active promotion code param

- src/1.0.0/js/autoCompleteUserForm.js
https://makingsense.atlassian.net/browse/DS-5379
> DS-5379 autocomplete form

- components/digital-trends/pre/digital-trends/entry-plans.php
- components/digital-trends/pre/digital-trends/vip-features.php
- src/1.0.0/css/components/features.css
- src/1.0.0/css/components/prices-plans.css
change pricing style
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5392)
> DS-5392 change pricing style 

- stripe/controllers/StripeCustomersController.php
- utils/SpreadSheetGoogle.php
https://makingsense.atlassian.net/browse/DS-5384
> DS-5384 spreadsheet vip column price

- components/SpeakerCard.php
- components/SpeakerCardComponent/CompanyFooter.php
- components/SpeakerCardComponent/CompanyLogo.php
- components/SpeakerCardComponent/Description.php
- components/SpeakerCardComponent/Label.php
- components/SpeakerCardComponent/SocialLinks.php
- components/SpeakerCardComponent/SpeakerBio.php
- components/SpeakerCardComponent/SpeakerInfo.php
- components/digital-trends/schedule/showSpeakersByDay.php
refactor: apply composition pattern in speaker card
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5399)
> DS-5399 speark card composition pattern

- components/SpeakerCardComponent/CompanyFooter.php
- components/SpeakerCardComponent/Label.php
- components/SpeakerCardComponent/SpeakerBio.php
- components/SpeakerCardComponent/SpeakerInfo.php
- components/digital-trends/schedule/showSpeakersByDay.php
- src/1.0.0/css/components/calendar.css
add interview card type
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5398)
> DS-5398 add interview type

- sponsors-interna.php
add navbar and target blank
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5400)
> DS-5400 change sponsor interna

- src/1.0.0/js/homeDigital.js
remove without form validations
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5402)
> DS-5402 remove validations without form

- components/digital-trends/schedule/showSpeakersByDay.php
replace text for event date
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5401)
> DS-5401 add day3 hour

- pages/digital-trends/during/checkout-success.php
- pages/digital-trends/during/checkout.php
- pages/digital-trends/during/digital-trends-registrado.php
- pages/digital-trends/during/digital-trends.php
- pages/digital-trends/during/home-registrado.php
- pages/digital-trends/during/home.php
https://makingsense.atlassian.net/browse/DS-5404
> DS-5404 init stage during

- sponsors-promo.php
add sponsor list in sponsors promo page
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5396)
> DS-5396 add sponsor list in sponsor

- sponsors-registrado.php
- sponsors.php
https://makingsense.atlassian.net/browse/DS-5405
> DS-5405 sponsorsList on resourcesLibrary Page

- components/digital-trends/during/central-video.php
- components/digital-trends/pre/central-video.php
- pages/digital-trends/during/home-registrado.php
- pages/digital-trends/during/home.php
change module content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5407)
> DS-5407 change module content

- components/digital-trends/during/faqs.php
- pages/digital-trends/during/home-registrado.php
- pages/digital-trends/during/home.php
add during faq
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5408)
>  DS-5408 during faq

- components/hello-bar.php
- pages/digital-trends/during/digital-trends.php
- pages/digital-trends/during/home-registrado.php
- pages/digital-trends/during/home.php
- src/1.0.0/css/components/hellobar.css
add new hello bar module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5411)
> DS-5411 hello bar during transition

- components/digital-trends/during/home/hello-module.php
add hello module for during
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5406)
> DS-5406 hello module during

- components/digital-trends/during/digital-trends/event-live.php
- config.php
https://makingsense.atlassian.net/browse/DS-5394
> DS-5394 event live component

- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/speakers.php
- src/1.0.0/css/components/calendar.css
[change calendar content](https://github.com/FromDoppler/emms24/commit/ffda22719e40b09a799f121a58f275fdd6ff5404)
[add smart tabs for calendar](https://github.com/FromDoppler/emms24/commit/7a27c272d1d2dedbdca8f1b0640281f686b8139c)
Related to : [Ticket](https://makingsense.atlassian.net/browse/DS-5416)
> DS-5416 smart schedulle buttons

- components/digital-trends/schedule/schedule.php
change button content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5416)
> DS-5416 schedulle button content

- components/sponsorsList.php
- pages/digital-trends/during/digital-trends.php
final modules structure for dt-live
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5418)
> DS-5418 dt page structure

- components/hello-bar.php
- sponsors.php
add hellobar module to sponsors
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5419)
> DS-5419 sponsors hellobar

- components/SpeakerCardComponent/Description.php
- components/SpeakerCardComponent/DescriptionButton.php
- components/digital-trends/schedule/mobile-carousel.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/css/general/constants.css
[add new button for speaker card](https://github.com/FromDoppler/emms24/commit/ed08f5ed56444450fbfa8acc194bc07dfbf91f66)
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5393)
> DS-5393 buttons live in speaker card

- components/hello-bar.php
add close tag
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5411)
> DS-5411 fix hello bar

- components/digital-trends/schedule/speakers.php
add initialize tab
Related to: [Ticket ](https://makingsense.atlassian.net/browse/DS-5416)
> DS-5416_fix_schedule

- components/digital-trends/during/digital-trends/event-live.php
- pages/digital-trends/during/digital-trends-registrado.php
- src/1.0.0/css/components/hero-conference.css
final dt-register modules structure
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5421)
> DS-5421 dt register modules

- components/hello-bar.php
add hidden-vip block
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5411)
> DS-5411 fix hellobar

- components/SpeakerCardComponent/DescriptionButton.php
- components/digital-trends/during/digital-trends/certificate/certificate.php
- components/digital-trends/during/digital-trends/event-live.php
- components/digital-trends/during/home/hello-module.php
- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/css/components/certificate-modal.css
- src/1.0.0/css/components/event-cards.css
- src/1.0.0/css/components/hero-conference.css
- src/1.0.0/css/components/newCalendar.css
- src/1.0.0/css/components/prices-plans.css
apply during demo feedback
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5422)
> DS-5422-feedback-qa-during

- utils/Relay.php
- utils/relay-templates/dt/dt-during-vip-template.html
- utils/relay-templates/dt/old/dt-during-template.html
add dt during emails in relay flow
Related to: [Ticket ](https://makingsense.atlassian.net/browse/DS-5388)
> DS-5388-dt-during-emails

- components/digital-trends/during/digital-trends/event-live.php
- components/digital-trends/during/register-form.php
- components/digital-trends/schedule/showSpeakersByDay.php
- config.php
- src/1.0.0/css/components/hero-conference.css
add transition in dt
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5423)
> DS-5423 transition dt

- stripe/controllers/StripeCustomersController.php
https://makingsense.atlassian.net/browse/DS-5427
> DS-5427 handle vip emails stripe

- components/digital-trends/during/digital-trends/head.php
- components/digital-trends/during/home/head.php
- components/share.php
- pages/digital-trends/during/digital-trends-registrado.php
- pages/digital-trends/during/digital-trends.php
- pages/digital-trends/during/home-registrado.php
- pages/digital-trends/during/home.php
- src/1.0.0/css/components/calendar.css
apply during share content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5428)
> DS-5428 share content

- components/digital-trends/pre/checkout/checkout-success.php
delete bullets
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5429)
> DS-5429 delete bullets

- src/components/intellInput.php
change intell input
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5435)
> DS-5435 change intell input

- components/digital-trends/during/digital-trends/event-live.php
- src/1.0.0/css/components/hero-conference.css
add new transition vip block
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5434)
> DS-5434 add transition vip block

- components/digital-trends/post/central-video.php
- pages/digital-trends/post/home-registrado.php
- pages/digital-trends/post/home.php
- src/1.0.0/css/components/hero-conference.css
add post central video module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5436)
> DS-5436 central video post

- components/digital-trends/during/digital-trends/event-live.php
change workshops links
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5412)
> DS-5412 live workshop link

- components/digital-trends/post/speakers-carousel.php
- pages/digital-trends/post/home-registrado.php
- pages/digital-trends/post/home.php
- src/1.0.0/css/components/speakers-list.css
add new speaker carousel post
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5437)
> DS-5437 speaker carousel post

- components/digital-trends/post/register-form.php
- components/digital-trends/post/register-withoutform.php
- pages/digital-trends/post/digital-trends.php
- src/1.0.0/css/pages/ecommerce.css
add post form module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5438)
> DS-5438 dt post form module

- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/speakers.php
add schedule post event
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5442)
> DS-5442-schedule-post

- components/SpeakerCardComponent/DescriptionButton.php
- src/1.0.0/css/components/calendar.css
add buttons post logic
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5443)
> DS-5443 buttos post logic

- components/digital-trends/post/digital-trends/hello-module.php
- components/digital-trends/post/digital-trends/hello-vip-module.php
- pages/digital-trends/post/digital-trends-registrado.php
- src/1.0.0/css/components/hero-registration.css
Add dt registered hello module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5439)
> DS-5439 digital trends egistered hello module

- components/digital-trends/post/digital-trends/vip-features.php
- pages/digital-trends/post/digital-trends-registrado.php
- src/1.0.0/css/components/features.css
add vip features post module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5446)
> DS-5446 vip feature post module

- pages/digital-trends/post/digital-trends-registrado.php
move module
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5431)
> DS-5431 move-module

- components/digital-trends/post/speaker-interna/event-recorded.php
- components/digital-trends/post/speaker-interna/promo-vip.php
- pages/digital-trends/post/digital-trends-registrado.php
- src/1.0.0/css/components/features.css
fix styles
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5448)
> DS-5448 speaker interna fix styles

- utils/Relay.php
- utils/relay-templates/dt/dt-post-vip-template.html
https://makingsense.atlassian.net/browse/DS-5449
> DS-5449 relay email post dt

- components/SpeakerCardComponent/Description.php
- components/SpeakerCardComponent/DescriptionButton.php
- components/digital-trends/post/digital-trends/head.php
- components/digital-trends/post/home/head.php
- components/digital-trends/pre/event-numbers.php
- components/digital-trends/schedule/schedule.php
- components/digital-trends/schedule/showSpeakersByDay.php
- components/share.php
- pages/digital-trends/post/digital-trends-registrado.php
- pages/digital-trends/post/digital-trends.php
- pages/digital-trends/post/home-registrado.php
- pages/digital-trends/post/home.php
- src/1.0.0/css/components/calendar.css
- src/1.0.0/js/counterAnimation.js
- src/components/speakersPostRegistrado.php
apply feedback post demo
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5450)
> DS-5450 feedback post

- components/SpeakerCardComponent/DescriptionButton.php
change speaker url in button
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5453)
> DS-5453 change button

- components/SpeakerCardComponent/DescriptionButton.php
enable interna for debate
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5455)
> DS-5455 enable interna debate

- components/digital-trends/post/register-form.php
https://makingsense.atlassian.net/browse/DS-5460
> DS-5460 button post content

- components/digital-trends/during/register-withoutform.php
- components/digital-trends/post/register-form.php
- components/digital-trends/post/register-withoutform.php
- components/digital-trends/pre/grid-event-types.php
- components/digital-trends/pre/register-withoutform.php
- components/register-form-component.php
- descarga-certificado.php
- ediciones-anteriores.php
- sponsors.php
- src/1.0.0/js/commonForm.js
- src/1.0.0/js/homeDigital.js
- src/1.0.0/js/previousEditions.js
- src/1.0.0/js/sponsors.js
add new form component
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5415)
> DS-5415 new form component
